# Generated by Django 4.2.11 on 2024-05-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail adresi'),
        ),
    ]
