# Generated by Django 4.2.11 on 2024-05-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0007_alter_profiles_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(upload_to='Media/Users/Avatars/', verbose_name='Profil Fotoğrafı'),
        ),
    ]
